BIOMES = [
  "Desert",
  "Taiga",
  "Mesa Plateau",
  "Ice Mountains",
  "Swampland M",
  "Birch Forest Hills",
  "Extreme Hills+ M",
  "Taiga M",
  "Jungle M",
  "MushroomIsland",
  "Savanna",
  "Roofed Forest M",
  "Mesa Plateau F",
  "Ice Plains Spikes",
  "Mega Taiga Hills",
  "FrozenRiver",
  "Ice Plains",
  "MushroomIslandShore",
  "ForestHills",
  "Forest",
  "Beach",
  "Roofed Forest",
  "Stone Beach",
  "Extreme Hills M",
  "Desert M",
  "JungleEdge",
  "Deep Ocean",
  "Extreme Hills",
  "Jungle",
  "Savanna Plateau",
  "DesertHills",
  "Birch Forest",
  "Mesa",
  "Mega Taiga",
  "Savanna M",
  "River",
  "Swampland",
  "Sunflower Plains",
  "Extreme Hills+",
  "Flower Forest",
  "Ocean",
  "TaigaHills",
  "Plains",
  "The End",
  "Hell",
  "Cold Taiga",
  "Birch Forest M",
  "JungleHills",
  "Savanna Plateau M",
  "Cold Beach",
  "Cold Taiga Hills"
]

ACHIEVEMENT_KEYS = [
'achievement.acquireIron',
'achievement.bakeCake',
'achievement.blazeRod',
'achievement.bookcase',
'achievement.breedCow',
'achievement.buildBetterPickaxe',
'achievement.buildFurnace',
'achievement.buildHoe',
'achievement.buildPickaxe',
'achievement.buildSword',
'achievement.buildWorkBench',
'achievement.cookFish',
'achievement.diamonds',
'achievement.diamondsToYou',
'achievement.enchantments',
'achievement.exploreAllBiomes',
'achievement.flyPig',
'achievement.fullBeacon',
'achievement.ghast',
'achievement.killCow',
'achievement.killEnemy',
'achievement.killWither',
'achievement.makeBread',
'achievement.mineWood',
'achievement.onARail',
'achievement.openInventory',
'achievement.overkill',
'achievement.overpowered',
'achievement.portal',
'achievement.potion',
'achievement.snipeSkeleton',
'achievement.spawnWither',
'achievement.theEnd',
'achievement.theEnd2'
]

KILLENTITY_KEYS = [
'stat.mobKills',
'stat.killEntity.Bat',
'stat.killEntity.Blaze',
'stat.killEntity.CaveSpider',
'stat.killEntity.Chicken',
'stat.killEntity.Cow',
'stat.killEntity.Creeper',
'stat.killEntity.Enderman',
'stat.killEntity.Endermite',
'stat.killEntity.Ghast',
'stat.killEntity.Guardian',
'stat.killEntity.EntityHorse',
'stat.killEntity.LavaSlime',
'stat.killEntity.Ozelot',
'stat.killEntity.Pig',
'stat.killEntity.PigZombie',
'stat.killEntity.Rabbit',
'stat.killEntity.Sheep',
'stat.killEntity.Shulker',
'stat.killEntity.Skeleton',
'stat.killEntity.Slime',
'stat.killEntity.Spider',
'stat.killEntity.Squid',
'stat.killEntity.Villager',
'stat.killEntity.Witch',
'stat.killEntity.Wolf',
'stat.killEntity.Zombie'
]