# Construct the URL we'll be calling
USER_CACHE_URI = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/usercache.json'
USER_URI_TEMPLATE = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/world/stats/UUID.json'

BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Birch Forest M",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "Desert M",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills M",
  "Extreme Hills+",
  "Extreme Hills+ M",
  "Flower Forest",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Hell",
  "Ice Mountains",
  "Ice Plains",
  "Ice Plains Spikes",
  "Jungle",
  "Jungle M",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Roofed Forest M",
  "Savanna",
  "Savanna M",
  "Savanna Plateau",
  "Savanna Plateau M",
  "Stone Beach",
  "Sunflower Plains",
  "Swampland",
  "Swampland M",
  "Taiga",
  "Taiga M",
  "TaigaHills",
  "The End"
]

ADVENTURING_TIME_BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills+",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Ice Mountains",
  "Ice Plains",
  "Jungle",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Savanna",
  "Savanna Plateau",
  "Stone Beach",
  "Swampland",
  "Taiga",
  "TaigaHills"
]

ACHIEVEMENT_KEYS = [
  'achievement.acquireIron',
  'achievement.bakeCake',
  'achievement.blazeRod',
  'achievement.bookcase',
  'achievement.breedCow',
  'achievement.buildBetterPickaxe',
  'achievement.buildFurnace',
  'achievement.buildHoe',
  'achievement.buildPickaxe',
  'achievement.buildSword',
  'achievement.buildWorkBench',
  'achievement.cookFish',
  'achievement.diamonds',
  'achievement.diamondsToYou',
  'achievement.enchantments',
  'achievement.exploreAllBiomes',
  'achievement.flyPig',
  'achievement.fullBeacon',
  'achievement.ghast',
  'achievement.killCow',
  'achievement.killEnemy',
  'achievement.killWither',
  'achievement.makeBread',
  'achievement.mineWood',
  'achievement.onARail',
  'achievement.openInventory',
  'achievement.overkill',
  'achievement.overpowered',
  'achievement.portal',
  'achievement.potion',
  'achievement.snipeSkeleton',
  'achievement.spawnWither',
  'achievement.theEnd',
  'achievement.theEnd2'
]

KILLENTITY_KEYS = [
  'stat.mobKills',
  'achievement.killEnemy',
  'stat.killEntity.Bat',
  'stat.killEntity.Blaze',
  'stat.killEntity.CaveSpider',
  'stat.killEntity.Chicken',
  'stat.killEntity.Cow',
  'achievement.killCow',
  'stat.killEntity.Creeper',
  'stat.killEntity.Enderman',
  'stat.killEntity.Endermite',
  'stat.killEntity.Ghast',
  'stat.killEntity.Guardian',
  'stat.killEntity.EntityHorse',
  'stat.killEntity.LavaSlime',
  'stat.killEntity.Ozelot',
  'stat.killEntity.Pig',
  'stat.killEntity.PigZombie',
  'stat.killEntity.Rabbit',
  'stat.killEntity.Sheep',
  'stat.killEntity.Shulker',
  'stat.killEntity.Skeleton',
  'stat.killEntity.Slime',
  'stat.killEntity.Spider',
  'stat.killEntity.Squid',
  'stat.killEntity.Villager',
  'stat.killEntity.Witch',
  'achievement.killWither',
  'stat.killEntity.Wolf',
  'stat.killEntity.Zombie'
]

TRAVEL_KEYS = [
  'stat.boatOneCm',
  'stat.climbOneCm',
  'stat.crouchOneCm',
  'stat.diveOneCm',
  'stat.fallOneCm',
  'stat.flyOneCm',
  'stat.horseOneCm',
  'stat.minecartOneCm',
  'stat.pigOneCm',
  'stat.sprintOneCm',
  'stat.swimOneCm',
  'stat.walkOneCm'
]

