# Construct the URL we'll be calling
USER_CACHE_URI = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/usercache.json'
USER_URI_TEMPLATE = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/world/stats/UUID.json'

BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Birch Forest M",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "Desert M",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills M",
  "Extreme Hills+",
  "Extreme Hills+ M",
  "Flower Forest",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Hell",
  "Ice Mountains",
  "Ice Plains",
  "Ice Plains Spikes",
  "Jungle",
  "Jungle M",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Roofed Forest M",
  "Savanna",
  "Savanna M",
  "Savanna Plateau",
  "Savanna Plateau M",
  "Stone Beach",
  "Sunflower Plains",
  "Swampland",
  "Swampland M",
  "Taiga",
  "Taiga M",
  "TaigaHills",
  "The End"
]

ADVENTURING_TIME_BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills+",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Ice Mountains",
  "Ice Plains",
  "Jungle",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Savanna",
  "Savanna Plateau",
  "Stone Beach",
  "Swampland",
  "Taiga",
  "TaigaHills"
]

ACHIEVEMENT_KEYS = [
  'achievement.openInventory',
  'achievement.mineWood',
  'achievement.buildWorkBench',
  'achievement.buildPickaxe',
  'achievement.buildFurnace',
  'achievement.acquireIron',
  'achievement.buildHoe',
  'achievement.makeBread',
  'achievement.bakeCake',
  'achievement.buildBetterPickaxe',
  'achievement.cookFish',
  'achievement.onARail',
  'achievement.buildSword',
  'achievement.killEnemy',
  'achievement.killCow',
  'achievement.flyPig',
  'achievement.snipeSkeleton',
  'achievement.diamonds',
  'achievement.portal',
  'achievement.ghast',
  'achievement.blazeRod',
  'achievement.potion',
  'achievement.theEnd',
  'achievement.theEnd2',
  'achievement.enchantments',
  'achievement.overkill',
  'achievement.bookcase',
  'achievement.exploreAllBiomes',
  'achievement.spawnWither',
  'achievement.killWither',
  'achievement.fullBeacon',
  'achievement.breedCow',
  'achievement.diamondsToYou',
  'achievement.overpowered'
]

ACHIEVEMENTS = {
  'achievement.openInventory' => 'Taking Inventory',
  'achievement.mineWood' => 'Getting Wood',
  'achievement.buildWorkBench' => 'Benchmarking',
  'achievement.buildPickaxe' => 'Time to Mine!',
  'achievement.buildFurnace' => 'Hot Topic',
  'achievement.acquireIron' => 'Acquire Hardware',
  'achievement.buildHoe' => 'Time to Farm!',
  'achievement.makeBread' => 'Bake Bread',
  'achievement.bakeCake' => 'The Lie',
  'achievement.buildBetterPickaxe' => 'Getting an Upgrade',
  'achievement.cookFish' => 'Delicious Fish',
  'achievement.onARail' => 'On a Rail',
  'achievement.buildSword' => 'Time to Strike!',
  'achievement.killEnemy' => 'Monster Hunter',
  'achievement.killCow' => 'Cow Tipper',
  'achievement.flyPig' => 'When Pigs Fly',
  'achievement.snipeSkeleton' => 'Sniper Duel',
  'achievement.diamonds' => 'DIAMONDS!',
  'achievement.portal' => 'We Need to Go Deeper',
  'achievement.ghast' => 'Return to Sender',
  'achievement.blazeRod' => 'Into Fire',
  'achievement.potion' => 'Local Brewery',
  'achievement.theEnd' => 'The End?',
  'achievement.theEnd2' => 'The End.',
  'achievement.enchantments' => 'Enchanter',
  'achievement.overkill' => 'Overkill',
  'achievement.bookcase' => 'Librarian',
  'achievement.exploreAllBiomes' => 'Adventuring Time',
  'achievement.spawnWither' => 'The Beginning?',
  'achievement.killWither' => 'The Beginning.',
  'achievement.fullBeacon' => 'Beaconator',
  'achievement.breedCow' => 'Repopulation',
  'achievement.diamondsToYou' => 'Diamonds to you!',
  'achievement.overpowered' => 'Overpowered'
}


KILLENTITY_KEYS = [
  'stat.mobKills',
  'achievement.killEnemy',
  'stat.killEntity.Bat',
  'stat.killEntity.Blaze',
  'stat.killEntity.CaveSpider',
  'stat.killEntity.Chicken',
  'stat.killEntity.Cow',
  'stat.killEntity.Creeper',
  'stat.killEntity.Enderman',
  'stat.killEntity.Endermite',
  'stat.killEntity.Ghast',
  'stat.killEntity.Guardian',
  'stat.killEntity.EntityHorse',
  'stat.killEntity.LavaSlime',
  'stat.killEntity.Ozelot',
  'stat.killEntity.Pig',
  'stat.killEntity.PigZombie',
  'stat.killEntity.Rabbit',
  'stat.killEntity.Sheep',
  'stat.killEntity.Shulker',
  'stat.killEntity.Skeleton',
  'stat.killEntity.Slime',
  'stat.killEntity.Spider',
  'stat.killEntity.Squid',
  'stat.killEntity.Villager',
  'stat.killEntity.Witch',
  'achievement.killWither',
  'stat.killEntity.Wolf',
  'stat.killEntity.Zombie'
]

TRAVEL_KEYS = [
  'stat.aviateOneCm',
  'stat.boatOneCm',
  'stat.climbOneCm',
  'stat.crouchOneCm',
  'stat.diveOneCm',
  'stat.fallOneCm',
  'stat.flyOneCm',
  'stat.horseOneCm',
  'stat.minecartOneCm',
  'stat.pigOneCm',
  'stat.sprintOneCm',
  'stat.swimOneCm',
  'stat.walkOneCm'
]

