# Construct the URL we'll be calling
USER_CACHE_URI = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/usercache.json'
USER_URI_TEMPLATE = 'https://raw.githubusercontent.com/qrush/pickaxe.club/master/world/stats/UUID.json'

MINIMUM_DAMAGE_DEALT = 75_000

MANUALLY_USED_KEYS = [
  'stat.playOneMinute',
  'stat.damageDealt',
  'stat.damageTaken',
  'stat.deaths',
  'stat.playOneMinute',
  'stat.playerKills'
]

GENERAL_STATS_KEYS = [
  'stat.playOneMinute',
  'stat.animalsBred',
  'stat.bannerCleaned',
  'stat.beaconInteraction',
  'stat.brewingstandInteraction',
  'stat.cakeSlicesEaten',
  'stat.cauldronFilled',
  'stat.cauldronUsed',
  'stat.chestOpened',
  'stat.damageDealt',
  'stat.damageTaken',
  'stat.deaths',
  'stat.playerKills',
  'stat.dispenserInspected',
  'stat.drop',
  'stat.dropperInspected',
  'stat.enderchestOpened',
  'stat.fishCaught',
  'stat.flowerPotted',
  'stat.furnaceInteraction',
  'stat.hopperInspected',
  'stat.itemEnchanted',
  'stat.jump',
  'stat.junkFished',
  'stat.leaveGame',
  'stat.mobKills',
  'stat.noteblockPlayed',
  'stat.noteblockTuned',
  'stat.recordPlayed',
  'stat.sleepInBed',
  'stat.sneakTime',
  'stat.talkedToVillager',
  'stat.timeSinceDeath',
  'stat.tradedWithVillager',
  'stat.trappedChestTriggered',
  'stat.treasureFished'
]

BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Birch Forest M",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "Desert M",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills M",
  "Extreme Hills+",
  "Extreme Hills+ M",
  "Flower Forest",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Hell",
  "Ice Mountains",
  "Ice Plains",
  "Ice Plains Spikes",
  "Jungle",
  "Jungle M",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Roofed Forest M",
  "Savanna",
  "Savanna M",
  "Savanna Plateau",
  "Savanna Plateau M",
  "Stone Beach",
  "Sunflower Plains",
  "Swampland",
  "Swampland M",
  "Taiga",
  "Taiga M",
  "TaigaHills",
  "The End"
]

ADVENTURING_TIME_BIOMES = [
  "Beach",
  "Birch Forest",
  "Birch Forest Hills",
  "Cold Beach",
  "Cold Taiga",
  "Cold Taiga Hills",
  "Deep Ocean",
  "Desert",
  "DesertHills",
  "Extreme Hills",
  "Extreme Hills+",
  "Forest",
  "ForestHills",
  "FrozenRiver",
  "Ice Mountains",
  "Ice Plains",
  "Jungle",
  "JungleEdge",
  "JungleHills",
  "Mega Taiga",
  "Mega Taiga Hills",
  "Mesa",
  "Mesa Plateau",
  "Mesa Plateau F",
  "MushroomIsland",
  "MushroomIslandShore",
  "Ocean",
  "Plains",
  "River",
  "Roofed Forest",
  "Savanna",
  "Savanna Plateau",
  "Stone Beach",
  "Swampland",
  "Taiga",
  "TaigaHills"
]

ACHIEVEMENT_KEYS = [
  'achievement.openInventory',
  'achievement.mineWood',
  'achievement.buildWorkBench',
  'achievement.buildPickaxe',
  'achievement.buildFurnace',
  'achievement.acquireIron',
  'achievement.buildHoe',
  'achievement.makeBread',
  'achievement.bakeCake',
  'achievement.buildBetterPickaxe',
  'achievement.cookFish',
  'achievement.onARail',
  'achievement.buildSword',
  'achievement.killEnemy',
  'achievement.killCow',
  'achievement.flyPig',
  'achievement.snipeSkeleton',
  'achievement.diamonds',
  'achievement.portal',
  'achievement.ghast',
  'achievement.blazeRod',
  'achievement.potion',
  'achievement.theEnd',
  'achievement.theEnd2',
  'achievement.enchantments',
  'achievement.overkill',
  'achievement.bookcase',
  'achievement.exploreAllBiomes',
  'achievement.spawnWither',
  'achievement.killWither',
  'achievement.fullBeacon',
  'achievement.breedCow',
  'achievement.diamondsToYou',
  'achievement.overpowered'
]

ACHIEVEMENTS = {
  'achievement.openInventory' => 'Taking Inventory',
  'achievement.mineWood' => 'Getting Wood',
  'achievement.buildWorkBench' => 'Benchmarking',
  'achievement.buildPickaxe' => 'Time to Mine!',
  'achievement.buildFurnace' => 'Hot Topic',
  'achievement.acquireIron' => 'Acquire Hardware',
  'achievement.buildHoe' => 'Time to Farm!',
  'achievement.makeBread' => 'Bake Bread',
  'achievement.bakeCake' => 'The Lie',
  'achievement.buildBetterPickaxe' => 'Getting an Upgrade',
  'achievement.cookFish' => 'Delicious Fish',
  'achievement.onARail' => 'On a Rail',
  'achievement.buildSword' => 'Time to Strike!',
  'achievement.killEnemy' => 'Monster Hunter',
  'achievement.killCow' => 'Cow Tipper',
  'achievement.flyPig' => 'When Pigs Fly',
  'achievement.snipeSkeleton' => 'Sniper Duel',
  'achievement.diamonds' => 'DIAMONDS!',
  'achievement.portal' => 'We Need to Go Deeper',
  'achievement.ghast' => 'Return to Sender',
  'achievement.blazeRod' => 'Into Fire',
  'achievement.potion' => 'Local Brewery',
  'achievement.theEnd' => 'The End?',
  'achievement.theEnd2' => 'The End.',
  'achievement.enchantments' => 'Enchanter',
  'achievement.overkill' => 'Overkill',
  'achievement.bookcase' => 'Librarian',
  'achievement.exploreAllBiomes' => 'Adventuring Time',
  'achievement.spawnWither' => 'The Beginning?',
  'achievement.killWither' => 'The Beginning.',
  'achievement.fullBeacon' => 'Beaconator',
  'achievement.breedCow' => 'Repopulation',
  'achievement.diamondsToYou' => 'Diamonds to you!',
  'achievement.overpowered' => 'Overpowered'
}

KILLENTITY_KEYS = [
  'stat.mobKills',
  'achievement.killEnemy',
  'stat.killEntity.Bat',
  'stat.killEntity.Blaze',
  'stat.killEntity.CaveSpider',
  'stat.killEntity.Chicken',
  'stat.killEntity.Cow',
  'stat.killEntity.Creeper',
  'stat.killEntity.Enderman',
  'stat.killEntity.Endermite',
  'stat.killEntity.Ghast',
  'stat.killEntity.Guardian',
  'stat.killEntity.EntityHorse',
  'stat.killEntity.LavaSlime',
  'stat.killEntity.MushroomCow',
  'stat.killEntity.Ozelot',
  'stat.killEntity.Pig',
  'stat.killEntity.PigZombie',
  'stat.killEntity.Rabbit',
  'stat.killEntity.Sheep',
  'stat.killEntity.Shulker',
  'stat.killEntity.Silverfish',
  'stat.killEntity.Skeleton',
  'stat.killEntity.Slime',
  'stat.killEntity.Spider',
  'stat.killEntity.Squid',
  'stat.killEntity.Villager',
  'stat.killEntity.Witch',
  'achievement.killWither',
  'stat.killEntity.Wolf',
  'stat.killEntity.Zombie'
]

KILLEDBY_KEYS = [
  'stat.entityKilledBy.Blaze',
  'stat.entityKilledBy.CaveSpider',
  'stat.entityKilledBy.Creeper',
  'stat.entityKilledBy.Enderman',
  'stat.entityKilledBy.Endermite',
  'stat.entityKilledBy.Ghast',
  'stat.entityKilledBy.Guardian',
  'stat.entityKilledBy.LavaSlime',
  'stat.entityKilledBy.PigZombie',
  'stat.entityKilledBy.Silverfish',
  'stat.entityKilledBy.Skeleton',
  'stat.entityKilledBy.Slime',
  'stat.entityKilledBy.Spider',
  'stat.entityKilledBy.Witch',
  'stat.entityKilledBy.Wolf',
  'stat.entityKilledBy.Zombie',
]

TRAVEL_KEYS = [
  'stat.aviateOneCm',
  'stat.boatOneCm',
  'stat.climbOneCm',
  'stat.crouchOneCm',
  'stat.diveOneCm',
  'stat.fallOneCm',
  'stat.flyOneCm',
  'stat.horseOneCm',
  'stat.minecartOneCm',
  'stat.pigOneCm',
  'stat.sprintOneCm',
  'stat.swimOneCm',
  'stat.walkOneCm'
]

CRAFTING_KEYS = [
  'stat.craftingTableInteraction',
  'stat.craftItem.minecraft.acacia_boat',
  'stat.craftItem.minecraft.acacia_door',
  'stat.craftItem.minecraft.acacia_fence',
  'stat.craftItem.minecraft.acacia_fence_gate',
  'stat.craftItem.minecraft.acacia_stairs',
  'stat.craftItem.minecraft.activator_rail',
  'stat.craftItem.minecraft.anvil',
  'stat.craftItem.minecraft.armor_stand',
  'stat.craftItem.minecraft.arrow',
  'stat.craftItem.minecraft.baked_potato',
  'stat.craftItem.minecraft.banner',
  'stat.craftItem.minecraft.beacon',
  'stat.craftItem.minecraft.bed',
  'stat.craftItem.minecraft.beetroot_soup',
  'stat.craftItem.minecraft.birch_boat',
  'stat.craftItem.minecraft.birch_door',
  'stat.craftItem.minecraft.birch_fence',
  'stat.craftItem.minecraft.birch_fence_gate',
  'stat.craftItem.minecraft.birch_stairs',
  'stat.craftItem.minecraft.blaze_powder',
  'stat.craftItem.minecraft.boat',
  'stat.craftItem.minecraft.book',
  'stat.craftItem.minecraft.bookshelf',
  'stat.craftItem.minecraft.bow',
  'stat.craftItem.minecraft.bowl',
  'stat.craftItem.minecraft.bread',
  'stat.craftItem.minecraft.brewing_stand',
  'stat.craftItem.minecraft.brick',
  'stat.craftItem.minecraft.brick_block',
  'stat.craftItem.minecraft.brick_stairs',
  'stat.craftItem.minecraft.bucket',
  'stat.craftItem.minecraft.cake',
  'stat.craftItem.minecraft.carpet',
  'stat.craftItem.minecraft.carrot_on_a_stick',
  'stat.craftItem.minecraft.cauldron',
  'stat.craftItem.minecraft.chest',
  'stat.craftItem.minecraft.chest_minecart',
  'stat.craftItem.minecraft.chorus_fruit_popped',
  'stat.craftItem.minecraft.clay',
  'stat.craftItem.minecraft.clock',
  'stat.craftItem.minecraft.coal',
  'stat.craftItem.minecraft.coal_block',
  'stat.craftItem.minecraft.cobblestone_wall',
  'stat.craftItem.minecraft.comparator',
  'stat.craftItem.minecraft.compass',
  'stat.craftItem.minecraft.cooked_beef',
  'stat.craftItem.minecraft.cooked_chicken',
  'stat.craftItem.minecraft.cooked_fish',
  'stat.craftItem.minecraft.cooked_mutton',
  'stat.craftItem.minecraft.cooked_porkchop',
  'stat.craftItem.minecraft.cooked_rabbit',
  'stat.craftItem.minecraft.cookie',
  'stat.craftItem.minecraft.crafting_table',
  'stat.craftItem.minecraft.dark_oak_door',
  'stat.craftItem.minecraft.dark_oak_fence',
  'stat.craftItem.minecraft.dark_oak_fence_gate',
  'stat.craftItem.minecraft.dark_oak_stairs',
  'stat.craftItem.minecraft.daylight_detector',
  'stat.craftItem.minecraft.detector_rail',
  'stat.craftItem.minecraft.diamond',
  'stat.craftItem.minecraft.diamond_axe',
  'stat.craftItem.minecraft.diamond_block',
  'stat.craftItem.minecraft.diamond_boots',
  'stat.craftItem.minecraft.diamond_chestplate',
  'stat.craftItem.minecraft.diamond_helmet',
  'stat.craftItem.minecraft.diamond_hoe',
  'stat.craftItem.minecraft.diamond_leggings',
  'stat.craftItem.minecraft.diamond_pickaxe',
  'stat.craftItem.minecraft.diamond_shovel',
  'stat.craftItem.minecraft.diamond_sword',
  'stat.craftItem.minecraft.dirt',
  'stat.craftItem.minecraft.dispenser',
  'stat.craftItem.minecraft.dropper',
  'stat.craftItem.minecraft.dye',
  'stat.craftItem.minecraft.emerald',
  'stat.craftItem.minecraft.emerald_block',
  'stat.craftItem.minecraft.enchanting_table',
  'stat.craftItem.minecraft.end_bricks',
  'stat.craftItem.minecraft.end_crystal',
  'stat.craftItem.minecraft.end_rod',
  'stat.craftItem.minecraft.ender_chest',
  'stat.craftItem.minecraft.ender_eye',
  'stat.craftItem.minecraft.fence',
  'stat.craftItem.minecraft.fence_gate',
  'stat.craftItem.minecraft.fermented_spider_eye',
  'stat.craftItem.minecraft.fire_charge',
  'stat.craftItem.minecraft.fishing_rod',
  'stat.craftItem.minecraft.flint_and_steel',
  'stat.craftItem.minecraft.flower_pot',
  'stat.craftItem.minecraft.furnace',
  'stat.craftItem.minecraft.furnace_minecart',
  'stat.craftItem.minecraft.glass',
  'stat.craftItem.minecraft.glass_bottle',
  'stat.craftItem.minecraft.glass_pane',
  'stat.craftItem.minecraft.glowstone',
  'stat.craftItem.minecraft.gold_block',
  'stat.craftItem.minecraft.gold_ingot',
  'stat.craftItem.minecraft.gold_nugget',
  'stat.craftItem.minecraft.golden_apple',
  'stat.craftItem.minecraft.golden_axe',
  'stat.craftItem.minecraft.golden_boots',
  'stat.craftItem.minecraft.golden_carrot',
  'stat.craftItem.minecraft.golden_chestplate',
  'stat.craftItem.minecraft.golden_helmet',
  'stat.craftItem.minecraft.golden_hoe',
  'stat.craftItem.minecraft.golden_leggings',
  'stat.craftItem.minecraft.golden_pickaxe',
  'stat.craftItem.minecraft.golden_rail',
  'stat.craftItem.minecraft.golden_shovel',
  'stat.craftItem.minecraft.golden_sword',
  'stat.craftItem.minecraft.hardened_clay',
  'stat.craftItem.minecraft.hay_block',
  'stat.craftItem.minecraft.heavy_weighted_pressure_plate',
  'stat.craftItem.minecraft.hopper',
  'stat.craftItem.minecraft.hopper_minecart',
  'stat.craftItem.minecraft.iron_axe',
  'stat.craftItem.minecraft.iron_bars',
  'stat.craftItem.minecraft.iron_block',
  'stat.craftItem.minecraft.iron_boots',
  'stat.craftItem.minecraft.iron_chestplate',
  'stat.craftItem.minecraft.iron_door',
  'stat.craftItem.minecraft.iron_helmet',
  'stat.craftItem.minecraft.iron_hoe',
  'stat.craftItem.minecraft.iron_ingot',
  'stat.craftItem.minecraft.iron_leggings',
  'stat.craftItem.minecraft.iron_pickaxe',
  'stat.craftItem.minecraft.iron_shovel',
  'stat.craftItem.minecraft.iron_sword',
  'stat.craftItem.minecraft.iron_trapdoor',
  'stat.craftItem.minecraft.item_frame',
  'stat.craftItem.minecraft.jukebox',
  'stat.craftItem.minecraft.jungle_boat',
  'stat.craftItem.minecraft.jungle_door',
  'stat.craftItem.minecraft.jungle_fence',
  'stat.craftItem.minecraft.jungle_fence_gate',
  'stat.craftItem.minecraft.jungle_stairs',
  'stat.craftItem.minecraft.ladder',
  'stat.craftItem.minecraft.lapis_block',
  'stat.craftItem.minecraft.lead',
  'stat.craftItem.minecraft.leather',
  'stat.craftItem.minecraft.leather_boots',
  'stat.craftItem.minecraft.leather_chestplate',
  'stat.craftItem.minecraft.leather_helmet',
  'stat.craftItem.minecraft.leather_leggings',
  'stat.craftItem.minecraft.lever',
  'stat.craftItem.minecraft.light_weighted_pressure_plate',
  'stat.craftItem.minecraft.lit_pumpkin',
  'stat.craftItem.minecraft.magma_cream',
  'stat.craftItem.minecraft.map',
  'stat.craftItem.minecraft.melon_block',
  'stat.craftItem.minecraft.melon_seeds',
  'stat.craftItem.minecraft.minecart',
  'stat.craftItem.minecraft.mossy_cobblestone',
  'stat.craftItem.minecraft.mushroom_stew',
  'stat.craftItem.minecraft.nether_brick',
  'stat.craftItem.minecraft.nether_brick_fence',
  'stat.craftItem.minecraft.nether_brick_stairs',
  'stat.craftItem.minecraft.netherbrick',
  'stat.craftItem.minecraft.noteblock',
  'stat.craftItem.minecraft.oak_stairs',
  'stat.craftItem.minecraft.painting',
  'stat.craftItem.minecraft.paper',
  'stat.craftItem.minecraft.piston',
  'stat.craftItem.minecraft.planks',
  'stat.craftItem.minecraft.prismarine',
  'stat.craftItem.minecraft.pumpkin_pie',
  'stat.craftItem.minecraft.pumpkin_seeds',
  'stat.craftItem.minecraft.purpur_block',
  'stat.craftItem.minecraft.purpur_pillar',
  'stat.craftItem.minecraft.purpur_slab',
  'stat.craftItem.minecraft.purpur_stairs',
  'stat.craftItem.minecraft.quartz_block',
  'stat.craftItem.minecraft.quartz_stairs',
  'stat.craftItem.minecraft.rabbit_stew',
  'stat.craftItem.minecraft.rail',
  'stat.craftItem.minecraft.red_sandstone',
  'stat.craftItem.minecraft.red_sandstone_stairs',
  'stat.craftItem.minecraft.redstone',
  'stat.craftItem.minecraft.redstone_block',
  'stat.craftItem.minecraft.redstone_lamp',
  'stat.craftItem.minecraft.redstone_torch',
  'stat.craftItem.minecraft.repeater',
  'stat.craftItem.minecraft.sandstone',
  'stat.craftItem.minecraft.sandstone_stairs',
  'stat.craftItem.minecraft.sea_lantern',
  'stat.craftItem.minecraft.shears',
  'stat.craftItem.minecraft.shield',
  'stat.craftItem.minecraft.sign',
  'stat.craftItem.minecraft.slime',
  'stat.craftItem.minecraft.slime_ball',
  'stat.craftItem.minecraft.snow',
  'stat.craftItem.minecraft.snow_layer',
  'stat.craftItem.minecraft.speckled_melon',
  'stat.craftItem.minecraft.sponge',
  'stat.craftItem.minecraft.spruce_boat',
  'stat.craftItem.minecraft.spruce_door',
  'stat.craftItem.minecraft.spruce_fence',
  'stat.craftItem.minecraft.spruce_fence_gate',
  'stat.craftItem.minecraft.spruce_stairs',
  'stat.craftItem.minecraft.stained_glass',
  'stat.craftItem.minecraft.stained_glass_pane',
  'stat.craftItem.minecraft.stained_hardened_clay',
  'stat.craftItem.minecraft.stick',
  'stat.craftItem.minecraft.sticky_piston',
  'stat.craftItem.minecraft.stone',
  'stat.craftItem.minecraft.stone_axe',
  'stat.craftItem.minecraft.stone_brick_stairs',
  'stat.craftItem.minecraft.stone_button',
  'stat.craftItem.minecraft.stone_hoe',
  'stat.craftItem.minecraft.stone_pickaxe',
  'stat.craftItem.minecraft.stone_pressure_plate',
  'stat.craftItem.minecraft.stone_shovel',
  'stat.craftItem.minecraft.stone_slab',
  'stat.craftItem.minecraft.stone_slab2',
  'stat.craftItem.minecraft.stone_stairs',
  'stat.craftItem.minecraft.stone_sword',
  'stat.craftItem.minecraft.stonebrick',
  'stat.craftItem.minecraft.sugar',
  'stat.craftItem.minecraft.tnt',
  'stat.craftItem.minecraft.tnt_minecart',
  'stat.craftItem.minecraft.torch',
  'stat.craftItem.minecraft.trapdoor',
  'stat.craftItem.minecraft.trapped_chest',
  'stat.craftItem.minecraft.tripwire_hook',
  'stat.craftItem.minecraft.wheat',
  'stat.craftItem.minecraft.wooden_axe',
  'stat.craftItem.minecraft.wooden_button',
  'stat.craftItem.minecraft.wooden_door',
  'stat.craftItem.minecraft.wooden_hoe',
  'stat.craftItem.minecraft.wooden_pickaxe',
  'stat.craftItem.minecraft.wooden_pressure_plate',
  'stat.craftItem.minecraft.wooden_shovel',
  'stat.craftItem.minecraft.wooden_slab',
  'stat.craftItem.minecraft.wooden_sword',
  'stat.craftItem.minecraft.wool',
  'stat.craftItem.minecraft.writable_book'
]

MINING_KEYS = [
  'stat.mineBlock.minecraft.acacia_fence',
  'stat.mineBlock.minecraft.acacia_fence_gate',
  'stat.mineBlock.minecraft.acacia_stairs',
  'stat.mineBlock.minecraft.activator_rail',
  'stat.mineBlock.minecraft.anvil',
  'stat.mineBlock.minecraft.beacon',
  'stat.mineBlock.minecraft.birch_fence',
  'stat.mineBlock.minecraft.birch_fence_gate',
  'stat.mineBlock.minecraft.birch_stairs',
  'stat.mineBlock.minecraft.bookshelf',
  'stat.mineBlock.minecraft.brick_block',
  'stat.mineBlock.minecraft.brick_stairs',
  'stat.mineBlock.minecraft.brown_mushroom',
  'stat.mineBlock.minecraft.brown_mushroom_block',
  'stat.mineBlock.minecraft.cactus',
  'stat.mineBlock.minecraft.carpet',
  'stat.mineBlock.minecraft.chest',
  'stat.mineBlock.minecraft.chorus_flower',
  'stat.mineBlock.minecraft.chorus_plant',
  'stat.mineBlock.minecraft.clay',
  'stat.mineBlock.minecraft.coal_block',
  'stat.mineBlock.minecraft.coal_ore',
  'stat.mineBlock.minecraft.cobblestone',
  'stat.mineBlock.minecraft.cobblestone_wall',
  'stat.mineBlock.minecraft.crafting_table',
  'stat.mineBlock.minecraft.dark_oak_fence',
  'stat.mineBlock.minecraft.dark_oak_fence_gate',
  'stat.mineBlock.minecraft.dark_oak_stairs',
  'stat.mineBlock.minecraft.daylight_detector',
  'stat.mineBlock.minecraft.deadbush',
  'stat.mineBlock.minecraft.detector_rail',
  'stat.mineBlock.minecraft.diamond_block',
  'stat.mineBlock.minecraft.diamond_ore',
  'stat.mineBlock.minecraft.dirt',
  'stat.mineBlock.minecraft.dispenser',
  'stat.mineBlock.minecraft.double_plant',
  'stat.mineBlock.minecraft.dropper',
  'stat.mineBlock.minecraft.emerald_block',
  'stat.mineBlock.minecraft.emerald_ore',
  'stat.mineBlock.minecraft.enchanting_table',
  'stat.mineBlock.minecraft.end_bricks',
  'stat.mineBlock.minecraft.end_rod',
  'stat.mineBlock.minecraft.end_stone',
  'stat.mineBlock.minecraft.ender_chest',
  'stat.mineBlock.minecraft.fence',
  'stat.mineBlock.minecraft.fence_gate',
  'stat.mineBlock.minecraft.furnace',
  'stat.mineBlock.minecraft.glass',
  'stat.mineBlock.minecraft.glass_pane',
  'stat.mineBlock.minecraft.glowstone',
  'stat.mineBlock.minecraft.gold_block',
  'stat.mineBlock.minecraft.gold_ore',
  'stat.mineBlock.minecraft.golden_rail',
  'stat.mineBlock.minecraft.gravel',
  'stat.mineBlock.minecraft.hardened_clay',
  'stat.mineBlock.minecraft.hay_block',
  'stat.mineBlock.minecraft.heavy_weighted_pressure_plate',
  'stat.mineBlock.minecraft.hopper',
  'stat.mineBlock.minecraft.ice',
  'stat.mineBlock.minecraft.iron_bars',
  'stat.mineBlock.minecraft.iron_block',
  'stat.mineBlock.minecraft.iron_ore',
  'stat.mineBlock.minecraft.jukebox',
  'stat.mineBlock.minecraft.jungle_fence',
  'stat.mineBlock.minecraft.jungle_fence_gate',
  'stat.mineBlock.minecraft.jungle_stairs',
  'stat.mineBlock.minecraft.ladder',
  'stat.mineBlock.minecraft.lapis_block',
  'stat.mineBlock.minecraft.lapis_ore',
  'stat.mineBlock.minecraft.leaves',
  'stat.mineBlock.minecraft.leaves2',
  'stat.mineBlock.minecraft.lever',
  'stat.mineBlock.minecraft.log',
  'stat.mineBlock.minecraft.log2',
  'stat.mineBlock.minecraft.melon_block',
  'stat.mineBlock.minecraft.monster_egg',
  'stat.mineBlock.minecraft.mossy_cobblestone',
  'stat.mineBlock.minecraft.mycelium',
  'stat.mineBlock.minecraft.nether_brick',
  'stat.mineBlock.minecraft.nether_brick_fence',
  'stat.mineBlock.minecraft.nether_brick_stairs',
  'stat.mineBlock.minecraft.netherrack',
  'stat.mineBlock.minecraft.noteblock',
  'stat.mineBlock.minecraft.oak_stairs',
  'stat.mineBlock.minecraft.obsidian',
  'stat.mineBlock.minecraft.packed_ice',
  'stat.mineBlock.minecraft.piston',
  'stat.mineBlock.minecraft.planks',
  'stat.mineBlock.minecraft.prismarine',
  'stat.mineBlock.minecraft.pumpkin',
  'stat.mineBlock.minecraft.purpur_block',
  'stat.mineBlock.minecraft.purpur_pillar',
  'stat.mineBlock.minecraft.purpur_slab',
  'stat.mineBlock.minecraft.purpur_stairs',
  'stat.mineBlock.minecraft.quartz_block',
  'stat.mineBlock.minecraft.quartz_ore',
  'stat.mineBlock.minecraft.quartz_stairs',
  'stat.mineBlock.minecraft.rail',
  'stat.mineBlock.minecraft.red_flower',
  'stat.mineBlock.minecraft.red_mushroom',
  'stat.mineBlock.minecraft.red_mushroom_block',
  'stat.mineBlock.minecraft.red_sandstone',
  'stat.mineBlock.minecraft.red_sandstone_stairs',
  'stat.mineBlock.minecraft.redstone_block',
  'stat.mineBlock.minecraft.redstone_lamp',
  'stat.mineBlock.minecraft.redstone_ore',
  'stat.mineBlock.minecraft.redstone_torch',
  'stat.mineBlock.minecraft.sand',
  'stat.mineBlock.minecraft.sandstone',
  'stat.mineBlock.minecraft.sandstone_stairs',
  'stat.mineBlock.minecraft.sapling',
  'stat.mineBlock.minecraft.sea_lantern',
  'stat.mineBlock.minecraft.slime',
  'stat.mineBlock.minecraft.snow',
  'stat.mineBlock.minecraft.snow_layer',
  'stat.mineBlock.minecraft.soul_sand',
  'stat.mineBlock.minecraft.sponge',
  'stat.mineBlock.minecraft.spruce_fence',
  'stat.mineBlock.minecraft.spruce_fence_gate',
  'stat.mineBlock.minecraft.spruce_stairs',
  'stat.mineBlock.minecraft.stained_glass',
  'stat.mineBlock.minecraft.stained_glass_pane',
  'stat.mineBlock.minecraft.stained_hardened_clay',
  'stat.mineBlock.minecraft.sticky_piston',
  'stat.mineBlock.minecraft.stone',
  'stat.mineBlock.minecraft.stone_brick_stairs',
  'stat.mineBlock.minecraft.stone_button',
  'stat.mineBlock.minecraft.stone_pressure_plate',
  'stat.mineBlock.minecraft.stone_slab',
  'stat.mineBlock.minecraft.stone_slab2',
  'stat.mineBlock.minecraft.stone_stairs',
  'stat.mineBlock.minecraft.stonebrick',
  'stat.mineBlock.minecraft.tallgrass',
  'stat.mineBlock.minecraft.tnt',
  'stat.mineBlock.minecraft.torch',
  'stat.mineBlock.minecraft.trapped_chest',
  'stat.mineBlock.minecraft.tripwire_hook',
  'stat.mineBlock.minecraft.vine',
  'stat.mineBlock.minecraft.waterlily',
  'stat.mineBlock.minecraft.web',
  'stat.mineBlock.minecraft.wooden_button',
  'stat.mineBlock.minecraft.wooden_pressure_plate',
  'stat.mineBlock.minecraft.wooden_slab',
  'stat.mineBlock.minecraft.wool',
  'stat.mineBlock.minecraft.yellow_flower'
]

FOOD_KEYS = [
  'stat.useItem.minecraft.apple',
  'stat.useItem.minecraft.baked_potato',
  'stat.useItem.minecraft.beef',
  'stat.useItem.minecraft.beetroot',
  'stat.useItem.minecraft.beetroot_soup',
  'stat.useItem.minecraft.bread',
  'stat.useItem.minecraft.cake',
  'stat.useItem.minecraft.carrot',
  'stat.useItem.minecraft.chicken',
  'stat.useItem.minecraft.chorus_fruit',
  'stat.useItem.minecraft.cooked_beef',
  'stat.useItem.minecraft.cooked_chicken',
  'stat.useItem.minecraft.cooked_fish',
  'stat.useItem.minecraft.cooked_mutton',
  'stat.useItem.minecraft.cooked_porkchop',
  'stat.useItem.minecraft.cooked_rabbit',
  'stat.useItem.minecraft.cookie',
  'stat.useItem.minecraft.fish',
  'stat.useItem.minecraft.golden_apple',
  'stat.useItem.minecraft.melon',
  'stat.useItem.minecraft.milk_bucket',
  'stat.useItem.minecraft.mushroom_stew',
  'stat.useItem.minecraft.mutton',
  'stat.useItem.minecraft.poisonous_potato',
  'stat.useItem.minecraft.porkchop',
  'stat.useItem.minecraft.potato',
  'stat.useItem.minecraft.pumpkin_pie',
  'stat.useItem.minecraft.rabbit',
  'stat.useItem.minecraft.rabbit_stew',
  'stat.useItem.minecraft.rotten_flesh',
  'stat.useItem.minecraft.spider_eye'
]